### ISSUE TITLE
Create a Many-To-Many relationship between Profiles and Images

### ISSUE THREAD

**Issue by haakonbu** [HoiskolensChemikerforening/website#107]
GDPR requires that we can locate all sensitive personal data - this includes pictures. We need a model so we can do this.

**Comment by hambro** [comment]
I guess you are thinking about the Image album funtionality that is "yet to be a feature".

The Profile model already knows what the image is, so you don't need a new model there. 
You might want to clarify which pictures are considered personal. I suggest we create a single issue for locating all PII data rather than creating one for each data type.

**Comment by haakonbu** [comment]
All images where a person is the motive is considered personal data [ref: https://www.datatilsynet.no/samfunnsomrader/internett-og-apper/bilder-pa-nett/]. If a user wants to access the data we have about them we have to be able to provide this - this includes pictures used for events, news, picture carousel etc. This also includes images that are stored, but not used.

**Comment by hambro** [comment]
If I'm understanding you correct:

**Any** picture we take, under almost all circumstances, (except 17th of May etc) must be tagged with every person in that photo. This requires a lot of effort
In addition, any photo posted online, Facebook or chemie.no, requires explicit consent everyone in the photo. We need some way of collecting individual approvals for this. 

Maybe a two-component solution is best. 1. Web gallery that is used to collect consent, with no advanced functionality. 2. Lightroom cloud subscription or 1 computer with Lightroom classic. This is to keep the sanity of the photographers as well as having tagged every person in any photo, should the ask for their data. 

I advise we read up on [Datatilsynets](www.datatilsynet.no) website, before jumping to any conclusions.
