### ISSUE TITLE
[Lockers] Some ownerships are incorrectly active

### ISSUE THREAD

**Issue by sindreoy** [HoiskolensChemikerforening/website#120]
Say two ownerships are pointing to locker n, and both ownerships are active. Locker n is only pointing to one ownership (the true owner), but this will cause conflicts when resetlockerstatus command is run next time. Then both ownerships will receive an email requesting reactivation. The incorrect user will also receive this email. First user to accept reactivation will get the locker, potentially giving the locker to an old user.

**Comment by anjarfr** [comment]
Fixed
