### ISSUE TITLE
[Events TOS] Specify that you are obliged to pay for your ticket

### ISSUE THREAD

**Issue by haakonbu** [HoiskolensChemikerforening/website#193]
Specify that you have to pay for your ticket when you don't withdraw from an event in time.

**Comment by Geirhov** [comment]
Lagde et punkt under generelt i samtykkerklæringen for arrangementer som heter betaling. 
Der står det følgende:
"Ved å melde deg på et arrangement plikter du deg til å betale for arrangementet hvis du ikke melder deg av innen avmeldingsfristen."
