### ISSUE TITLE
Return HttpResponseRedirect on Account Refill (Shop)

### ISSUE THREAD

**Issue by haakonbu** [HoiskolensChemikerforening/website#212]
If the form is valid, the view should redirect the user using a `HttpResponseRedirect` (as indicated by [docs](https://docs.djangoproject.com/en/2.2/topics/forms/)).

This is to avoid accidentally resubmitting the form on refresh, which would result in the person getting two refills.

**Comment by emedd33** [comment]
Fixed in Order_item branch which was merged now
