### ISSUE TITLE
Possibility for pre registration for events

### ISSUE THREAD

**Issue by bendikstoasannes** [HoiskolensChemikerforening/website#251]
Kjellerstyret vil ofte "reservere" plasser til arrangementer. Da ser det også litt kulere ut når det er en del som er påmeldt.

**Comment by yoonsiko** [comment]
Er dette egentlig nødvendig? Kjellerstyret har jo aldri hatt problemer med å fylle opp arrangementene sine.

**Comment by bendikstoasannes** [comment]
Nei, nødvendig er det absolutt ikke. Men det var et ønske fra dem, i hvert fall. Det var vel en pSitting som hadde litt dårlig påmelding en gang i tiden
