### ISSUE TITLE
Make it possible to see companions for an event

### ISSUE THREAD

**Issue by bendikstoasannes** [HoiskolensChemikerforening/website#265]
https://hc.ntnu.no/events/social/adminlist/id
pHaestkom hadde blitt glade hvis de slapp å spørre oss for å få oversikt over hvem som har påmeldt eksternt følge og navnet deres.

**Comment by haaklov** [comment]
Fikset, men ikke optimalisert. Når det er mange attributes for et arrangement, går headeren med attributes "utenfor" skjermen.
