### ISSUE TITLE
Locker - duplicate LockerUser glitch

### ISSUE THREAD

**Issue by hambro** [HoiskolensChemikerforening/website#47]
A handful of LockerUsers were duplicated during the import. This won't happen with the live code, but the few duplicates cause errors all around the place and should be fixed in the database. 

```
Internal Server Error: /bokskap/mine-skap

MultipleObjectsReturned at /bokskap/mine-skap
get() returned more than one LockerUser -- it returned 2!
```

**Comment by sindreoy** [comment]
Some duplicates have registered one locker to each duplicate. May be troublesome

**Comment by hambro** [comment]
Fixed.
`from lockers.models import Locker, Ownership, LockerUser
from django.db.models import Count

duplicates = LockerUser.objects.values('email').annotate(Count('id')).order_by().filter(id__count__gt=1)
user_count= LockerUser.objects.all().count()

for dupe in duplicates:
	dupe_ownerships = Ownership.objects.filter(user__email=dupe['email'])
	first_dupe, last_dupe = dupe_ownerships.first(), dupe_ownerships.last()
	to_delete = first_dupe.user
	first_dupe.user = last_dupe.user
	first_dupe.save()
	to_delete.delete()

print(user_count-LockerUser.objects.all().count())`
