### ISSUE TITLE
Typo in bedpres

### ISSUE THREAD

**Issue by cherrybeans** [HoiskolensChemikerforening/website#59]
![screenshot from 2018-01-31 20-02-22](https://user-images.githubusercontent.com/25204035/35641911-c93a3f38-06c1-11e8-8e76-4c8582f868ba.png)

Should say "Vennligst" not "Vennligs".

**Comment by hambro** [comment]
Another typo as well: The event title has some gibberish at the end on the "social event detail"-page.
