### ISSUE TITLE
Squashed picture in sidebar menu

### ISSUE THREAD

**Issue by cherrybeans** [HoiskolensChemikerforening/website#61]
![screenshot from 2018-01-31 20-25-56](https://user-images.githubusercontent.com/25204035/35642939-018b4bcc-06c5-11e8-95d5-9d876553fe02.png)

**Comment by hambro** [comment]
Should be fixed in design-iteration branch, take a look there

**Comment by hambro** [comment]
Hopefully fixed in [9d92984](https://github.com/HoiskolensChemikerforening/website/commit/9d929849ee7ff1835c095603b73411c62327682a).
