### ISSUE TITLE
Fikse Eskild sin weird ass kode

### ISSUE THREAD

**Issue by sindreoy** [HoiskolensChemikerforening/website#62]
Eskild har pusha noe weird som ikke funker. Merkelig bug når du submitter sladder hvor ikke teksten er korrekt.
![mattefest](https://user-images.githubusercontent.com/14299736/35643232-fb7772fa-06c5-11e8-901a-15412fe534ab.jpg)

**Comment by haakonbu** [comment]
Huffda :(
