### ISSUE TITLE
Split up requirements into local and prod

### ISSUE THREAD

**Issue by cherrybeans** [HoiskolensChemikerforening/website#70]
And use pip-tools to make better requirement files. Right now installing from requirements often fails due to a few packages not working on e.g. Windows, or issues with postgresql.

**Comment by cherrybeans** [comment]
Fixed in split-requirements branch

**Comment by hambro** [comment]
Smooth work!

**Comment by hambro** [comment]
[Fixed](https://github.com/HoiskolensChemikerforening/website/pull/77)
