### ISSUE TITLE
Possibility to email all attendees

### ISSUE THREAD

**Issue by sindreoy** [HoiskolensChemikerforening/website#76]
Button to send email to all members enrolled for event. Updates, change of time, other important information.

**Comment by hambro** [comment]
This is what I’d define “Who cares”-functionality (https://blog.yesinsights.com/how-to-prioritize-what-product-features-to-build-next/ <https://blog.yesinsights.com/how-to-prioritize-what-product-features-to-build-next/>). This is something we must discuss, as we have limited resources to development and long term maintanence. 

What I suggest is that the “download attendee list” is used. It is then possible to select the email column in Excel and paste it into the preferred email client.

**Comment by hambro** [comment]
This is what I’d define “Who cares”-functionality (https://blog.yesinsights.com/how-to-prioritize-what-product-features-to-build-next/ <https://blog.yesinsights.com/how-to-prioritize-what-product-features-to-build-next/>). This is something we must discuss, as we have limited resources to development and long term maintanence. 

What I suggest is that the “download attendee list” is used. It is then possible to select the email column in Excel and paste it into the preferred email client.
![Website](https://user-images.githubusercontent.com/8371798/35816459-11815d80-0a9b-11e8-8e72-e6cdd84ef467.png)
![Email client](https://user-images.githubusercontent.com/8371798/35816505-2cabdf90-0a9b-11e8-8dd9-f509af3071d6.png)
