### ISSUE TITLE
Creator of event needs "edit event"-permission

### ISSUE THREAD

**Issue by haakonbu** [HoiskolensChemikerforening/website#82]
Creators of events need "edit event"-permission for their own events.

**Comment by hambro** [comment]
Simple fix: Add "edit event" perm to all users with "add event". 
Complex: Remove "edit event" perm check, but check author == request.user and maybe draft == True.

**Comment by hambro** [comment]
This is now fixed by adding edit_bedpres and edit_social to the relevant permission groups.
