### ISSUE TITLE
Counting attendees doesn't account for externals

### ISSUE THREAD

**Issue by sindreoy** [HoiskolensChemikerforening/website#83]
When someone enrolls for an event with external companion, they are allowed to do so even if there aren't enough slots for both of them. The result is that the counter exceeds slot limit, see screenshots
<img width="1680" alt="skjermbilde 2018-02-27 kl 14 38 52" src="https://user-images.githubusercontent.com/14299736/36731749-f1ed4302-1bcb-11e8-9d50-26b299f0789b.png">

<img width="1680" alt="skjermbilde 2018-02-27 kl 14 35 17" src="https://user-images.githubusercontent.com/14299736/36731663-a883bfd4-1bcb-11e8-88f2-93f686d52840.png">

**Comment by hambro** [comment]
I'd say "wont fix" because it requires a lot of extra work, with very small consequences.
